# -*- coding: utf-8 -*-
# Deployment settings for GardenWars.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.0/s3e/makefile_builder/mkb.py', '--open-with-wmlaunchpad', 'C:/Users/Flash/Documents/mobile_workspace/GardenWars/GardenWars.mkb', '--deploy-only']
mkb = 'C:/Users/Flash/Documents/mobile_workspace/GardenWars/GardenWars.mkb'
mkf = ['c:\\marmalade\\6.0\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.0\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.0\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.0\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\flash\\appdata\\roaming\\marmalade\\packages\\6.0.1\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\flash\\appdata\\roaming\\marmalade\\packages\\6.0.1\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\flash\\appdata\\roaming\\marmalade\\packages\\6.0.1\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.0\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.0\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.0\\modules\\iwgxfont\\iwgxfont.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('C:/Users/Flash/Documents/mobile_workspace/GardenWars/data/grass.png', 'grass.png', 0),
    ('C:/Users/Flash/Documents/mobile_workspace/GardenWars/data/stone.png', 'stone.png', 0),
    ('C:/Users/Flash/Documents/mobile_workspace/GardenWars/data/dirt.png', 'dirt.png', 0),
    ('C:/Users/Flash/Documents/mobile_workspace/GardenWars/data/character.png', 'character.png', 0),
    ('C:/Users/Flash/Documents/mobile_workspace/GardenWars/data/star.png', 'star.png', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'GardenWars'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'GardenWars'
    long_caption = 'GardenWars'
    version = [0, 0, 1]
    config = ['C:/Users/Flash/Documents/mobile_workspace/GardenWars/data/app.icf']
    data_dir = 'C:/Users/Flash/Documents/mobile_workspace/GardenWars/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Debug_GardenWars_VC10_arm/GardenWars.s3e',
                   'release' : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Release_GardenWars_VC10_arm/GardenWars.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Debug_GardenWars_VC10_gcc_mips/GardenWars.so',
                   'release' : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Release_GardenWars_VC10_gcc_mips/GardenWars.so',
                 },
         'x86' : {
                   'debug'   : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Debug_GardenWars_VC10_x86/GardenWars.s86',
                   'release' : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Release_GardenWars_VC10_x86/GardenWars.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Debug_GardenWars_VC10_gcc_arm/GardenWars.s3e',
                   'release' : r'C:/Users/Flash/Documents/mobile_workspace/GardenWars/build_gardenwars_vc10/Release_GardenWars_VC10_gcc_arm/GardenWars.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
