#define SCREEN_WIDTH Iw2DGetSurfaceWidth()
#define SCREEN_HEIGHT Iw2DGetSurfaceHeight()

#define TILE_WIDTH 100
#define TILE_HEIGHT 80

#define WORLD_TILES_WIDTH 128
#define WORLD_TILES_HEIGHT 128

#define WORLD_PIXELS_WIDTH WORLD_TILES_WIDTH*TILE_WIDTH
#define WORLD_PIXELS_HEIGHT WORLD_TILES_HEIGHT*TILE_HEIGHT